### PR TITLE
about links section fixes

### PR DESCRIPTION
**Pull request by kamdz**
before: 
http://i.imgur.com/sztynNQ.png
after:
http://i.imgur.com/fNbuq9R.png

before:
http://i.imgur.com/5bLVfOw.png
after:
http://i.imgur.com/pajewuu.png

### CODE REVIEW

**Comment by kamdz** [comment]
yep, another mistake

**Comment by sindresorhus** [comment]
Please stop opening new pull requests. Just edit the existing one ;)

**Comment by kamdz** [comment]
Yes, I know. But I deleted fork from pull request and I couldn't edit it anymore. So I need to create new one.

**Comment by sindresorhus** [comment]
> But I **deleted fork from pull request**

Don't do that then.

**Pull request closed without merging**
